#!/bin/bash
set -e
pushd ~/git/nix-config
sudo nixos-rebuild switch &>nixos-switch.log || (
  cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
echo "git commit -am $gen"
popd
